name: Generate PDF

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pdf"
  cancel-in-progress: false

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: ./puppeteer/package-lock.json
      - name: Setup Chrome
        run: |
          sudo npx @puppeteer/browsers install chrome@stable --install-deps
      - name: Install puppeteer
        run: npm install
      - name: Run puppeteer script
        run: node index.js
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        run: |
          gh release create "pdf-${{ github.run_number }}" ./August-Herrstrom-CV.pdf \
            --title "pdf-${{ steps.date.outputs.date }}" \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}