name: Generate PDF

on:
  workflow_dispatch:

concurrency:
  group: "pdf"
  cancel-in-progress: false

jobs:
  generate-pdf:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-dependencies: true
      - name: Check Chrome version
        run: chrome --version
        
      - name: Install puppeteer
        run: npm install
      - name: Run puppeteer script
        run: npm start